# Generated by Django 3.0.8 on 2021-01-01 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20201219_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='visible_usuarios',
            field=models.BooleanField(default=False, verbose_name='¿Visible para usuarios registrados?'),
        ),
    ]
