# Generated by Django 3.0.8 on 2021-01-01 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_page_visible_usuarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='visible_usuarios',
        ),
        migrations.AlterField(
            model_name='page',
            name='visible',
            field=models.CharField(choices=[('0', 'Visitantes'), ('1', 'Usuarios registrados')], default='0', max_length=1, verbose_name='Visible para'),
        ),
    ]
